config/routes.rb
Rails.application.routes.draw do
  get 'pages/produkty'

  get 'pages/procmydla'

  get 'pages/kontakty'

root :to => redirect('/ideas')
  resources :ideas

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def produkty
  end

  def procmydla
  end

  def kontakty
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ideas/_form.html.erb
<%= form_for @idea, :html => {:multipart => true} do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Jaké jsou vaše zkušenosti?" %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :description, "Vaše jméno:" %><br>
    <%= f.text_field :description %>
  </div>
 </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<%= image_tag "sova - velká.png", class: "uvodni"%>
<h1>Mirčina mýdla</h1>

<h3>...a jiné kosmetické radůstky</h3>

<br>
<br>
Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
<br>
<br>
Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
<br>
<br>
<br>
<br>

<%= image_tag "mýdlový košíček 1.jpg", class: "nahled"%>
<%= image_tag "mýdlový jahodový dortík 1.jpg", class: "nahled"%>
<%= image_tag "koule 2.jpg", class: "nahled"%>
<%= image_tag "mýdlový košíček 2.jpg", class: "nahled"%>
<%= image_tag "koule 1.jpg", class: "nahled"%>

<br>
<br>
<br>
<br>

<h4>Co si u nás můžete objednat?</h4>
<br>
- Lorem ipsum<br>
- Lorem ipsum<br>
- Lorem ipsum<br>
- Lorem ipsum<br>
<br>
<br>
<br>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Projekt:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Popis:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Výsledek:</strong>
  <%= image_tag(@idea.picture_url, :width => 600) if @idea.picture.present? %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
 <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css" />
<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Mirčina mýdla</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/pages/produkty">Produkty</a></li>
        <li class="active"><a href="/pages/procmydla">Proč mýdla?</a></li>
        <li class="active"><a href="/pages/kontakty">Kontakty a objednávky</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    Rails Girls 2014
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
</html>

app/views/pages/kontakty.html.erb
<h1>Kontakty a objednávky</h1>
<br>
<br>
<br>
<br>
<br>
<p> Lorem ipsum Lorem ipsum</p>
<p> Lorem ipsum Lorem ipsum</p>
<p> Lorem ipsum Lorem ipsum</p>
<p> Lorem ipsum</p>
<br>
<br>
<br>
<br>
<%= image_tag "mapa.png", class: "uvodni"%>
<br>
<br>
<br>
<br>

app/views/pages/procmydla.html.erb
<h1>Proč právě vyrábění mýdel?</h1>
<br>
<br>
<br>
<br>
<br>
<p>Jmenuji se Mirka, je mi 42 let a neustále něco tvořím a vytvářím již od ranného dětství.
<br>
<br>
Rok 2013 byl pro mě velmi zlomový. Tak jak to v této době bývá, i mě dohnala hektická doba a já se přepracovala. Musela jsem úplně zastavit a 2 měsíce odpočívat. V té době jsem měla prostor na dávnou touhu,  začít s výrobou mýdla. 
<br>
<br>
Mýdla jsou vyráběna ručně tzv. metodou zastudena, což zaručuje zachování všech výživných složek v mýdlech. Nepoužívám zbytečné chemikálie jako např. umělé konzervanty, stabilizátory, parabeny či umělé tenzidy které jen vysušují a dráždí citlivou pokožku. K výrobě používám výlučně rostlinné oleje, esence a barviva určená pro kosmetiku. 
<br>
<br>
Každé mýdlo testuji pH papírkem a další testování je na mé početné rodině a přátelích. 
<br>
<br>
Postupně se prokousávám všemi předpisy, které jsou třeba k oficialní výbobě mýdla a kosmetiky. Mým snem je otevřít si vlastní mýdlarnu s kreativní dílnou. Tak doufám, že se podaří. </p>
<br>
<br>
<br>
<br>

<%= image_tag "vyroba1.jpg", class: "vyroba"%>
<%= image_tag "vyroba3.jpg", class: "vyroba"%>
<%= image_tag "vyroba2.jpg", class: "vyroba"%>
<%= image_tag "vyroba3.jpg", class: "vyroba"%>
<%= image_tag "vyroba2.jpg", class: "vyroba"%>
<%= image_tag "vyroba1.jpg", class: "vyroba"%>
<%= image_tag "vyroba1.jpg", class: "vyroba"%>
<%= image_tag "vyroba2.jpg", class: "vyroba"%>
<%= image_tag "vyroba3.jpg", class: "vyroba"%>

<br>
<br>
<br>
<br>
<br>
<br>

app/views/pages/produkty.html.erb
<h1>Vyberte si z nejrůznějších vůní, tvarů a barev...</h1>
<br>
<br>
<br>
<br>
<br>
<br>
<p>Pro přípravu mýdel používám jen kvalitní oleje, esence a tak. Proto jsou mýdla vhodná i pro citlivou pokožku nebo pro děti. </p>
<br>
<br>
<br>
<br>

<h3>Mýdlové košíčky</h3>
<p>Dva druhy mýdla v jednom: našlehané bílé a žluto-oranžové z olejů. Zkrátka užijte si dvakrát. </p>
<p>Cena: 44 Kč</p>
<br>
<%= image_tag "mýdlový košíček 1.jpg", class: "produkty"%>
<%= image_tag "mýdlový košíček 2.jpg", class: "produkty"%>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h3>Jogurtové mýdlo</h3>
<p>Mýdlo z jogurtovou přísadou a s vůní jahod.</p>
<p>Cena: 33 Kč</p>
<br>
<%= image_tag "jahodovy.jpg", class: "produkty"%>
<%= image_tag "jahodovy2.jpg", class: "produkty"%>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h3>Šumivé koule do vany</h3>
<p>Prošumí koupel a vaši pokožku zanechají hebkou a voňavou.</p>
<p>Cena: 11 Kč</p>
<br>
<%= image_tag "koule 1.jpg", class: "produkty"%>
<%= image_tag "koule 2.jpg", class: "produkty"%>
<%= image_tag "koule 3.jpg", class: "produkty"%>
<br><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h3>Mýdlový jahodový dortík</h3>
<p>Jeden kousek z jahodového dortu - souhra tří druhů mýdla.</p>
<p>Cena: 55 Kč</p>
<br>
<%= image_tag "mýdlový jahodový dortík 1.jpg", class: "produkty"%>
<%= image_tag "mýdlový jahodový dortík 2.jpg", class: "produkty"%>